### ISSUE TITLE
Missing Changelog

### ISSUE THREAD

**Issue by Turbo87** [ivanvanderbyl/ember-cli-d3-primitive#10]
It seems that this repo is missing a changelog file and/or release notes. Without something like that it seems very hard to find out what actually changed between releases. It would be awesome if you could add something like this for future releases.

**Comment by ivanvanderbyl** [comment]
Hey @Turbo87 that's a great idea. I'll add one for future updates.

**Comment by ivanvanderbyl** [comment]
I've added a changelog in the latest release.

**Comment by Turbo87** [comment]
Awesome, thanks a lot!
