### ISSUE TITLE
Some resources appear to be missing

### ISSUE THREAD

**Issue by mike-north** [ivanvanderbyl/ember-cli-d3-primitive#12]
- [ ] Two mixins are used [here](https://github.com/ivanvanderbyl/ember-cli-d3-shape/commit/04542517124fbc4a24cb67716acae4d6fe27f132#diff-ceb667e3b119476459f6996167845481R5) but are not defined in the project
- [ ] A helper is used [here](https://github.com/ivanvanderbyl/ember-cli-d3-shape/blob/master/tests/dummy/app/templates/application.hbs#L9) but it's not registered with the container.

It's possible that everything is working as expected with the library -- these are just parts of the dummy app

**Comment by ivanvanderbyl** [comment]
Ah yes, they were be part of this app, now part of maximum-plaid. I just haven't updated the dummy app/removed it. Here's the commit https://github.com/ivanvanderbyl/ember-cli-d3-shape/commit/0a58531ea4400d7a243f2072fb20d62a2df294e1

**Comment by ivanvanderbyl** [comment]
Should be resolved by https://github.com/ivanvanderbyl/ember-cli-d3-shape/pull/13
