### ISSUE TITLE
Trying to Follow Demo App throws error:

### ISSUE THREAD

**Issue by vip3rousmango** [ivanvanderbyl/ember-cli-d3-primitive#2]
Hello!

Trying to follow your demo app to get a donut chart to load but I get:
`Could not find module d3-path imported from d3-shape`
when trying to do so.

Is there something missing as I'm unable to complete the demo using the latest version of Ember / Ember CLI.
## 

Al Romano
@vip3rousmango
alexander@virtuallycreative.ca
CA: +1-647-518-0587

**Comment by ivanvanderbyl** [comment]
What version of ember / ember-cli?

**Comment by vip3rousmango** [comment]
version: 2.3.0-beta.1
enode: 5.1.1
npm: 2.14.10
os: darwin x64
ember-cli 1.13.15

## 

Al Romano
@vip3rousmango
alexander@virtuallycreative.ca
CA: +1-647-518-0587

**Comment by ivanvanderbyl** [comment]
@vip3rousmango it looks like a breaking change in the way the dependent d3 packages are being compiled. I'll update the addon to fix this today.

**Comment by ivanvanderbyl** [comment]
@vip3rousmango should be fixed for you in `0.4.0`
