### ISSUE TITLE
Update for D3 v4 release?

### ISSUE THREAD

**Issue by mike-north** [ivanvanderbyl/ember-cli-d3-primitive#20]
Not sure what, if anything, needs to be done in order to make this usable with D3 v4.1.

**Comment by ivanvanderbyl** [comment]
I think ideally we should just point this to the d3 npm package and lock
the version in.

**Comment by ivanvanderbyl** [comment]
Thought on how this could work: 

Include `d3@4.1` as the only dep, then  in index.js lookup all the dependencies on `d3` and add them to the vendor tree.

**Comment by ivanvanderbyl** [comment]
Then release this in lock step versioning of d3

**Comment by mike-north** [comment]
@ivanvanderbyl sounds good. Check out https://github.com/mike-north/ember-rx-shim for my take on something similar
