### ISSUE TITLE
example component imports non-existent mixins

### ISSUE THREAD

**Issue by ballPointPenguin** [ivanvanderbyl/ember-cli-d3-primitive#8]
In the example (d3-donut) there are two lines:

```
import  Area from 'ember-cli-d3-shape/mixins/area';
import Dimensions from 'ember-cli-d3-shape/mixins/dimensions';
```

but there is no 'mixins' directory provided and those files do not exist.
It is a bit unclear how to properly include these things.

**Comment by ivanvanderbyl** [comment]
Well spotted, sorry about that. This is a purposeful regression, and I forgot to update the readme. I've decided it's best to provide this only as a shim for D3 v4 as others are depending on it only for this purpose, and provide those mixins in a new addon [maximum-plaid](https://github.com/ivanvanderbyl/maximum-plaid/) which will be a more full featured graphing library.

**Comment by ballPointPenguin** [comment]
OK cool. I'm digging into all of that now. I will hopefully be able to contribute to docs once I find the right pattern(s).

**Comment by ivanvanderbyl** [comment]
Todo: 
- [ ] Remove dummy app, and reference `maximum-plaid`.
